name: Build
on:
  push:
    branches:
      - main
    paths:
      - .dockerignore
      - Dockerfile
      - rootfs/**
      - .github/workflows/build.yaml
  pull_request:
    branches:
      - main
    paths:
      - .dockerignore
      - Dockerfile
      - rootfs/**
      - .github/workflows/build.yaml
  schedule:
    - cron: 0 23 * * 6
  workflow_dispatch:
    inputs:
      publish:
        description: Publish docker images
        required: true
        default: false
        type: boolean
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: docker/github-builder/.github/workflows/build.yml@17bd7d64200cae4ba58ffc099934e8012ae320f2 # v1.10.0
    with:
      output: image
      push: ${{ (github.event_name == 'push' && github.ref_name == 'main') || github.event_name == 'schedule' || inputs.publish == true }}
      context: .
      file: Dockerfile
      platforms: linux/arm64,linux/amd64
      cache: true
      meta-images: |
        ghcr.io/${{ github.repository }}
        docker.io/${{ github.repository_owner }}/archlinux
      meta-tags: |
        type=schedule,prefix=base-,pattern={{date 'YYYYMMDD'}}
        type=raw,value=base,enable={{is_default_branch}}
        type=raw,value=latest,enable={{is_default_branch}}
      meta-flavor: |
        latest=${{ github.ref_name == 'main' }}
      build-args: |
        CACHE_BUST=${{ github.run_id }}-${{ github.run_attempt }}
    secrets:
      registry-auths: |
        - registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        - registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
